---
- name: print all variable with diff method
  hosts: localhost
  vars_files:
    - external_vars.yml
  tasks:
    - name: Test external dict key value
      debug:
        msg: "{{external_example_key}}"
    - name: test external_dict values
      debug:
        msg: "{{external_dict.dict_key}}"
    - name: test external_inline_dict
      debug:
        msg: "{{external_inline_dict['inline_dict_key']}}"
    - name: test external_named_list
      debug:
        msg: "{{external_named_list[2]}}"
    - name: test external_inline_named_list
      debug:
        msg: "{{external_inline_named_list}}"
